-- Frozen baseline of existing operational stores, ported to PostgreSQL.
-- Text UUID/time/JSON fields preserve the existing serialization contract.
CREATE TABLE jobs (
    job_id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    status TEXT NOT NULL,
    priority INTEGER NOT NULL,
    max_attempts INTEGER NOT NULL,
    backoff_seconds DOUBLE PRECISION NOT NULL,
    max_backoff_seconds DOUBLE PRECISION NOT NULL,
    retryable_outcomes_json TEXT NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    active_attempt_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    available_at TEXT NOT NULL,
    cancellation_requested_at TEXT,
    cancelled_at TEXT
);

CREATE TABLE execution_attempts (
    attempt_id TEXT PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES jobs(job_id),
    attempt_number INTEGER NOT NULL,
    worker_id TEXT NOT NULL,
    input_ref TEXT NOT NULL,
    lease_token TEXT NOT NULL UNIQUE,
    lease_expires_at TEXT NOT NULL,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    outcome TEXT,
    failure_kind TEXT,
    error_code TEXT,
    error TEXT,
    output_ref TEXT,
    UNIQUE(job_id, attempt_number)
);

CREATE TABLE job_transitions (
    transition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES jobs(job_id),
    from_status TEXT,
    to_status TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE job_idempotency (
    idempotency_key TEXT PRIMARY KEY,
    job_id TEXT NOT NULL UNIQUE REFERENCES jobs(job_id),
    created_at TEXT NOT NULL
);

CREATE TABLE job_tasks (
    job_id TEXT PRIMARY KEY REFERENCES jobs(job_id),
    task_json TEXT NOT NULL
);

CREATE TABLE job_outputs (
    job_id TEXT PRIMARY KEY REFERENCES jobs(job_id),
    result_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX jobs_claim_order
    ON jobs(status, available_at, priority DESC, created_at);
CREATE INDEX attempts_active_lease
    ON execution_attempts(job_id, ended_at, lease_expires_at);


CREATE TABLE goals (
    goal_id              TEXT PRIMARY KEY,
    origin               TEXT NOT NULL,
    objective            TEXT NOT NULL,
    confidence_threshold DOUBLE PRECISION NOT NULL,
    status               TEXT NOT NULL,
    plan_confidence      DOUBLE PRECISION,
    created_at           TEXT NOT NULL
);

CREATE TABLE projects (
    project_id  TEXT PRIMARY KEY,
    goal_id     TEXT NOT NULL,
    title       TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    ordinal     INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE planned_tasks (
    task_id         TEXT PRIMARY KEY,
    project_id      TEXT NOT NULL,
    goal_id         TEXT NOT NULL,
    skill           TEXT NOT NULL,
    payload_json    TEXT NOT NULL,
    depends_on_json TEXT NOT NULL DEFAULT '[]',
    status          TEXT NOT NULL DEFAULT 'pending',
    confidence      DOUBLE PRECISION,
    result_json     TEXT,
    error           TEXT,
    ordinal         INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE goal_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id TEXT NOT NULL,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    reason TEXT,
    affected_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL
);

CREATE TABLE goal_repositories (
    goal_id TEXT PRIMARY KEY,
    repository_id TEXT NOT NULL,
    base_revision TEXT NOT NULL,
    base_commit_sha TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

ALTER TABLE planned_tasks ADD COLUMN job_id TEXT;

ALTER TABLE planned_tasks ADD COLUMN resolved_payload_json TEXT;

CREATE TABLE tasks (
    task_id           TEXT,
    task_type         TEXT,
    assigned_agent    TEXT,
    status            TEXT,
    confidence        DOUBLE PRECISION,
    retry_count       INTEGER,
    escalated_to_human INTEGER,
    failure_reason    TEXT,
    issued_at         TEXT,
    completed_at      TEXT,
    payload_json      TEXT,
    result_json       TEXT,
    PRIMARY KEY (task_id, status)
);

CREATE TABLE review_queue (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id        TEXT    UNIQUE NOT NULL,
    task_type      TEXT,
    skill_id       TEXT    NOT NULL DEFAULT '',
    agent_id       TEXT    NOT NULL DEFAULT '',
    agent_output   TEXT    NOT NULL DEFAULT '{}',
    sla_deadline   TEXT,
    confidence     DOUBLE PRECISION,
    payload        TEXT,
    status         TEXT    NOT NULL DEFAULT 'pending',
    created_at     TEXT    NOT NULL,
    reviewed_at    TEXT,
    reviewer_notes TEXT,
    goal_id        TEXT
    ,planned_task_id TEXT
    ,attempt_id TEXT
);

CREATE TABLE artifact_versions (
    identity_key   TEXT    NOT NULL,
    version        INTEGER NOT NULL,
    content        TEXT    NOT NULL,
    content_hash   TEXT    NOT NULL,
    filename       TEXT    NOT NULL,
    language       TEXT,
    artifact_type  TEXT,
    task_id        TEXT    NOT NULL,
    skill          TEXT    NOT NULL,
    created_at     TEXT    NOT NULL,
    attempt_artifact_key TEXT,
    PRIMARY KEY (identity_key, version)
);

CREATE UNIQUE INDEX artifact_attempt_identity ON artifact_versions(attempt_artifact_key) WHERE attempt_artifact_key IS NOT NULL;
