from typing import Protocol


class RegistryStore(Protocol):
    def register_agent(self, agent_id: str, metadata: dict) -> None: ...
    def get_agent(self, agent_id: str) -> dict | None: ...
    def list_agents(self) -> list[dict]: ...
    def deregister_agent(self, agent_id: str) -> None: ...
    def get_agent_skills(self, agent_id: str) -> list[dict]: ...
