from __future__ import annotations

import os
import re

from pydantic import BaseModel, Field, field_validator

_ID_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")


class AgentScaffoldParams(BaseModel):
    agent_id: str
    agent_name: str = Field(min_length=1)
    description: str = Field(min_length=1)
    task_types: list[str] = Field(min_length=1)
    llm_override: str | None = None
    confidence_threshold: float = Field(default=0.80, ge=0.0, le=1.0)

    @field_validator("agent_id")
    @classmethod
    def validate_agent_id(cls, value: str) -> str:
        if not _ID_PATTERN.match(value):
            raise ValueError(
                "agent_id must be lowercase alphanumeric with underscores, starting with a letter"
            )
        return value


class SkillScaffoldParams(BaseModel):
    skill_id: str
    skill_name: str = Field(min_length=1)
    parent_agent_id: str = Field(min_length=1)
    description: str = Field(min_length=1)
    input_schema: dict[str, str] = Field(min_length=1)
    output_schema: dict[str, str] = Field(min_length=1)

    @field_validator("skill_id")
    @classmethod
    def validate_skill_id(cls, value: str) -> str:
        if not _ID_PATTERN.match(value):
            raise ValueError(
                "skill_id must be lowercase alphanumeric with underscores, starting with a letter"
            )
        return value


class ScaffoldResult(BaseModel):
    success: bool
    files_created: list[str] = []
    agent_id: str | None = None
    skill_id: str | None = None
    error: str | None = None
    warning: str | None = None


class ForgeConflictError(Exception):
    def __init__(self, path: str):
        self.path = path
        super().__init__(f"Forge conflict: {path} already exists")


def _to_pascal_case(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_"))


_AGENT_TEMPLATE = '''\
from core.contracts.contracts import TaskContract, SkillManifest, SkillEntry
from core.pulsar.registry import PulsarRegistry
from core.aether.client import AetherClient
import logging

logger = logging.getLogger(__name__)

AGENT_ID = "{agent_id}"
AGENT_NAME = "{agent_name}"
VERSION = "0.1.0"
CONFIDENCE_THRESHOLD = {confidence_threshold}


class {class_name}:
    """
    {description}

    Task types: {task_types_comment}

    Generated by Galaxz Forge. Implement execute() before registering
    this agent for production routing.
    """

    def __init__(self, pulsar: PulsarRegistry, aether: AetherClient):
        self.pulsar = pulsar
        self.aether = aether
        self._register()

    def _register(self) -> None:
        manifest = SkillManifest(
            agent_id=AGENT_ID,
            agent_name=AGENT_NAME,
            version=VERSION,
            skills=[],
            confidence_threshold=CONFIDENCE_THRESHOLD,
        )
        self.pulsar.register(manifest)
        logger.info(f"[{{AGENT_ID}}] registered with Pulsar")

    def execute(self, contract: TaskContract) -> TaskContract:
        # TODO: implement agent logic
        raise NotImplementedError(
            f"{{AGENT_NAME}} execute() is not yet implemented. "
            "See agents/{agent_id}/agent.py"
        )
'''


_SKILL_TEMPLATE = '''\
from typing import Any


def {skill_id}(payload: dict, llm_client: Any) -> dict:
    """
    {description}

    Input:
{input_doc}
    Output:
{output_doc}
    Generated by Galaxz Forge.
    """
{input_extractions}
    # TODO: implement skill logic using llm_client
    raise NotImplementedError(
        "{skill_name} is not yet implemented. "
        "See agents/{parent_agent_id}/skills/{skill_id}.py"
    )
'''


def scaffold_skill(
    params: SkillScaffoldParams, base_path: str = "."
) -> ScaffoldResult:
    agent_dir = f"{base_path}/agents/{params.parent_agent_id}"
    if not os.path.exists(agent_dir):
        return ScaffoldResult(
            success=False,
            skill_id=params.skill_id,
            error=f"Parent agent '{params.parent_agent_id}' not found at {agent_dir}",
        )

    skill_path = f"{agent_dir}/skills/{params.skill_id}.py"
    if os.path.exists(skill_path):
        raise ForgeConflictError(skill_path)

    input_doc = "".join(f"        {k} ({v})\n" for k, v in params.input_schema.items())
    output_doc = "".join(f"        {k} ({v})\n" for k, v in params.output_schema.items())
    input_extractions = "".join(
        f'    {k} = payload.get("{k}")\n' for k in params.input_schema
    )

    skill_py = _SKILL_TEMPLATE.format(
        skill_id=params.skill_id,
        description=params.description,
        skill_name=params.skill_name,
        parent_agent_id=params.parent_agent_id,
        input_doc=input_doc,
        output_doc=output_doc,
        input_extractions=input_extractions,
    )

    files_created: list[str] = []
    try:
        os.makedirs(f"{agent_dir}/skills", exist_ok=True)
        with open(skill_path, "w") as f:
            f.write(skill_py)
        files_created.append(skill_path)
    except OSError as e:
        return ScaffoldResult(
            success=False,
            files_created=files_created,
            skill_id=params.skill_id,
            error=f"File write failed: {str(e)}",
        )

    return ScaffoldResult(
        success=True,
        files_created=files_created,
        skill_id=params.skill_id,
    )


def scaffold_agent(
    params: AgentScaffoldParams, base_path: str = "."
) -> ScaffoldResult:
    target_dir = f"{base_path}/agents/{params.agent_id}"
    if os.path.exists(target_dir):
        raise ForgeConflictError(target_dir)

    files_created: list[str] = []

    agent_py = _AGENT_TEMPLATE.format(
        agent_id=params.agent_id,
        agent_name=params.agent_name,
        confidence_threshold=params.confidence_threshold,
        class_name=_to_pascal_case(params.agent_id),
        description=params.description,
        task_types_comment=", ".join(params.task_types),
    )

    try:
        os.makedirs(f"{target_dir}/skills", exist_ok=False)

        init_path = f"{target_dir}/__init__.py"
        with open(init_path, "w") as f:
            f.write("")
        files_created.append(init_path)

        agent_path = f"{target_dir}/agent.py"
        with open(agent_path, "w") as f:
            f.write(agent_py)
        files_created.append(agent_path)

        skills_init_path = f"{target_dir}/skills/__init__.py"
        with open(skills_init_path, "w") as f:
            f.write("")
        files_created.append(skills_init_path)

    except OSError as e:
        return ScaffoldResult(
            success=False,
            files_created=files_created,
            agent_id=params.agent_id,
            error=f"File write failed: {str(e)}",
        )

    try:
        from core.contracts.contracts import SkillManifest
        from core.pulsar.registry import PulsarRegistry

        registry = PulsarRegistry()
        manifest = SkillManifest(
            agent_id=params.agent_id,
            agent_name=params.agent_name,
            version="0.1.0",
            skills=[],
            health_endpoint=f"local://agents/{params.agent_id}",
        )
        registry.register(manifest)
    except Exception as e:
        return ScaffoldResult(
            success=False,
            files_created=files_created,
            agent_id=params.agent_id,
            error=f"Files scaffolded but Pulsar registration failed: {str(e)}",
        )

    return ScaffoldResult(
        success=True,
        files_created=files_created,
        agent_id=params.agent_id,
        warning=(
            f"Agent '{params.agent_id}' is registered but not yet routable. "
            "Add it to Andromeda's routing config to enable task routing."
        ),
    )
